### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by icebob** [small-tech/jsdb#3]
Hi, 

congratulation, it's a great project. Do you plan to make a benchmark where you compare the speed of jsdb with others (e.g nedb, lokijs, dexie...etc)?

**Comment by aral** [comment]
Hi @icebob,

Thank you for the kind words.

I’m not a huge fan of benchmarks as they usually don’t end up measuring real-world performance within the different use cases for different tools but I’m not averse to anyone else running them and reporting the results. I’m sure there are things we can learn from them. (I don’t see myself having the time to do this in the near future, though.)

JSDB is optimised for [Small Web](https://ar.al/2020/08/07/what-is-the-small-web/) use, so its main characteristics are that it offers constant reads and writes at the expense of memory use (since we don’t farm people for their data, we don’t need to store huge amounts of it).

I’ve attempted to summarise the [performance characteristics](https://github.com/small-tech/jsdb#performance-characteristics) and [memory usage and initial load and compaction times](https://github.com/small-tech/jsdb#memory-usage) in the readme. Do these help at all?

If this is something you’d like to help with, please, by all means keep this issue open and report back your findings.

And I hope you enjoy playing with JSDB :)

**Comment by herrbasan** [comment]
Benchmarks would be rather useful as from the outset I don't see JSDB being too different from nedb or lokijs. From what i've gathered the main difference is to use eval instead of parsing json. I could imagine that this brings a performance boost, but it also might not :)

I'm also a bit nervous about eval in general.

**Comment by aral** [comment]
The main difference between JSDB and nedb/lokijs, etc., is:

  - The transparent API (you mostly feel like you’re working with native arrays and objects, they just happen to be persisted).
  - It writes out to an append-only JavaScript log instead of JSON, hence you have consistent and fast reads and writes.

And, most importantly, it’s [small tech](https://small-tech.org/about/#small-technology) so it wasn’t created for building surveillance-based Silicon Valley “startup” bullshit :) So it’s really not competing with tools that might have been created for that reason.

Again, not opposed to benchmarks but I don’t see myself setting aside time to create them. I’m going to close this but please feel free to re-open it or a different one if you create any benchmarks or find any that exist.
